### PR TITLE
This is the file including all code and images

### PR DESCRIPTION
**Pull request by ultimatetau**
This is an attempt at HW 2. I believe everything is in order.

### CODE REVIEW

**Comment by zingale** [comment]
you are supposed to do your homework by cloning the repo named homework2-ultimatetau that was created when you accepted the github classroom invite link, and then you just push your work to that repo.

You do not do a pull request to this repo.

**Comment by ultimatetau** [comment]
It for some reason kept prompting me for my username and password. I
assumed it was required to fork it.

I'm slightly confused.. I cloned the repo but when I went to send it back,
it wouldnt accept the push!

**Comment by zingale** [comment]
You need to clone your repo, not the class repo.

So for you, you'd clone

https://github.com/phy504-sbu/homework2-ultimatetau

Then you should be able to push back to that

**Comment by ultimatetau** [comment]
Ah, I'm sorry. I think I've completed this correctly now. Thank you!

**Pull request closed without merging**
